source 'http://rubygems.org'

gem 'rails', '3.0.3'
gem 'pg', '0.10.1'
gem 'haml', '3.0.25'
gem 'compass', '0.10.6'
gem 'simple_form', '1.3.0'
gem 'attribute_normalizer', '0.3.1'
gem 'dalli', '1.0.2'
gem 'exceptional', '2.0.32'
gem 'acts-as-taggable-on', '2.0.6'
gem 'httparty', '0.7.3'
gem 'hashie', '1.0.0'

group :test do
  gem 'capybara', '~> 0'
  gem 'rspec-rails', '~> 2'
  gem 'cucumber-rails', '~> 0'
  gem 'autotest', '~> 4'
  gem 'factory_girl_rails', '~> 1.1.beta1'
  gem 'database_cleaner', '~> 0'
  gem 'launchy', '~> 0'
  gem 'webmock', '~> 1'
  gem 'cover_me', '~> 1.0.0.rc5'
end